Bootstrap:docker
From:nfcore/base

%labels
	MAINTAINER Viktor henmyr <viktor.henmyr@skane.se>
	DESCRIPTION Singularity container for TWIST-BRCA pipeline
	VERSION 0.0.3

%environment
	PATH=/opt/conda/envs/twist-brca/bin:/opt/bin:$PATH
	PICARD_HOME=/opt/conda/envs/twist-brca/share/picard-2.18.26-0/
	export PERL5LIB=$PERL5LIB:/opt/conda/envs/twist-brca/lib/site_perl/5.26.2/
	export PERL5LIB=$PERL5LIB:/opt/conda/envs/twist-brca/lib/site_perl/5.26.2/x86_64-linux-thread-multi/
	export PERL5LIB=$PERL5LIB:/opt/bin/

%files
    twist-brca.yaml /
	/data/bnf/sw/melt/MELTv2.1.5/MELT.jar /opt/
    ../bin/ /opt
%post
	rm -rf /var/lib/apt/lists/*
	apt -y clean
	apt -y update
    apt -y install libz-dev build-essential cmake libxml2-dev libcurl4-openssl-dev libssl-dev make
	/opt/conda/bin/conda env create -f /twist-brca.yaml
#   /opt/conda/envs/twist-brca/bin/cpanm Path::Tiny --force
# 	/opt/conda/envs/twist-brca/bin/cpanm MongoDB::Collection
	/opt/conda/envs/twist-brca/bin/cpanm JSON
    /opt/conda/envs/twist-brca/bin/pip install genmod
	/opt/conda/bin/conda clean -a
